project:
  type: website
  output-dir: docs

website:
  title: "Mutua Kilai, PhD"
  favicon: "files/logo.png"
  page-footer: 
    left: "&copy; 2024, Dr. Mutua Kilai"
    center: "Lecturer and Data Scientist"
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      
  navbar:
    pinned: true
    background: "#0040ff"
    left:
      - text: "About"
        file: index.qmd
      - text: "Consulting Services"
        file: consulting.qmd
      - text: "Post-Graduate Courses"
        file: teaching.qmd
      - text: "Undergraduate Courses"
        file: undergraduate.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Publications"
        file: publication.qmd
      - text: "CV"
        file: cv.qmd
  sidebar:
    - title: "Undergraduate Courses"
      background: light
      contents: 
        - section: "Introduction"
          contents: 
            - underg/index.qmd
        - section: "Kirinyaga University"
          contents: 
            - text: "SPS 2467 Statistical Model Building"
              file: underg/kyu.qmd
            - text: "SPS 2349 Tests of Hypothesis"
              file: underg/toh.qmd
            - text: "HES 2213 Design and Analysis of Experiments II"
              file: underg/hes.qmd
            - text: "SPA 2403 Survival Analysis"
              file: underg/surv.qmd
            - text: "Introduction to R"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

